# See claude code environment variables documents at https://code.claude.com/docs/en/settings
[env]

[tools]
claude = "latest"
python = "3.12"
uv = "latest"
ruff = "latest"

# === Tasks
[tasks.venv-create]
description = "✨ Create Python virtual environment (.venv)"
run = "uv venv"

[tasks.venv-remove]
description = "💥 Remove Python virtual environment folder (.venv)"
run = "rm -r .venv"

[tasks.inst]
description = "💾 Install Python dependencies (dev, test, doc, etc.) via uv"
run = "uv sync --all-extras"

[tasks.cov]
description = "🧪 Run code coverage test"
run = """
.venv/bin/pytest \
  -s \
  --tb=native \
  --rootdir=. \
  --cov=laptop \
  --cov-report term-missing \
  --cov-report html:htmlcov \
  tests
"""
